// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDl-CptzXRXClnorHOEB1VEZ3qc0cOqgA',
    appId: '1:933732335023:web:fd1c6ba947793a8df0835a',
    messagingSenderId: '933732335023',
    projectId: 'dulces-app',
    authDomain: 'dulces-app.firebaseapp.com',
    storageBucket: 'dulces-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLty9MqJIZB2Pe3mj1-PWrIQwxH40ml9Q',
    appId: '1:933732335023:android:6ee6fdc7c12e6dacf0835a',
    messagingSenderId: '933732335023',
    projectId: 'dulces-app',
    storageBucket: 'dulces-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1QaIIl7PAeSoJDnE9c36GSEVNGB32tsY',
    appId: '1:933732335023:ios:5552e5fb0fdfb226f0835a',
    messagingSenderId: '933732335023',
    projectId: 'dulces-app',
    storageBucket: 'dulces-app.appspot.com',
    iosClientId: '933732335023-3lqnc7ltrk1uu5s5754fl9t8ai5k6sg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.buildlayout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1QaIIl7PAeSoJDnE9c36GSEVNGB32tsY',
    appId: '1:933732335023:ios:5552e5fb0fdfb226f0835a',
    messagingSenderId: '933732335023',
    projectId: 'dulces-app',
    storageBucket: 'dulces-app.appspot.com',
    iosClientId: '933732335023-3lqnc7ltrk1uu5s5754fl9t8ai5k6sg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.buildlayout',
  );
}
